version: '2' 
services:

  gemfoundation_gmo_keys_server:
    image: gemfoundation_gmo_keys_server:${RELEASE_TAG}
    restart: always
    container_name: gmo_keys_server
    ports:
     - 9004:80

  gemfoundation_model_execution_worker:
    image: coreoasis/model_execution_worker:${RELEASE_TAG}
    restart: always
    container_name: gmo_worker
    volumes:
     - ${HOME}/oasis-test/model_data/GMO/:/var/oasis/model_data/GMO/DR
     - ${HOME}/upload:/var/www/oasis/upload:rw
     - ${HOME}/download:/var/www/oasis/download:rw
     - /tmp:/tmp
    # Prevent the machine craching due to excessive memory pressure
    mem_limit: 50g
    # Vulnerability data is loaded in shm
    shm_size: 15g
    # Required to allow GDB
    privileged: true
    environment:
     - MODEL_SUPPLIER_ID=GMO
     - MODEL_VERSION_ID=DR
     - LOCK_FILE = '/tmp/tmp_ktools_lock_file'
     - DO_CLEAR_WORKING = True
     - KTOOLS_BATCH_COUNT=-1
     - RABBIT_PORT=5672
     - MYSQL_PORT=3306
    links:
     - oasis_mysql:mysql
     - oasis_rabbit:rabbit

